# Configure a stereo receiver using an IR blaster
---
- hosts: stereo_blasters
  gather_facts: true
  roles:
    - name: docker role
      role: docker

    - name: lirc-blaster role
      role: lirc-blaster
      vars:
        LIRC_BLASTER_SERIAL: "DN028UT5"
        LIRC_BLASTER_REMOTES:
          - smsl-rc1.lircd.conf

    - name: lirc-web role
      role: lirc-web
