# Configure a stereo receiver using an IR blaster
---
- hosts: stereo_blaster
  gather_facts: true
  roles:
    - name: docker role
      role: elgeeko1-docker-ansible

    - name: lirc-blaster role
      role: elgeeko1-lirc-blaster-ansible
      vars:
        LIRC_BLASTER_SERIAL: "DN028UT5"
        LIRC_BLASTER_REMOTES:
          - smsl-rc1.lircd.conf
          - yamaha-ras13.lircd.conf
